<a href="https://colab.research.google.com/github/mohit3015/ai-ml-learning/blob/main/py_numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
# list

l1 = [3, 4, 5, 7, 2]
print(l1)

[3, 4, 5, 7, 2]


1. Array Creation Functions


* np.array() → Create array from list
* np.zeros() → Array filled with 0
* np.ones() → Array filled with 1
* np.empty() → Empty array
* np.arange() → Range of values
* np.linspace() → Equal spaced numbers
* np.eye() → Identity matrix
* np.full() → Fill with specific value

3. Mathematical Functions


* np.add() → Addition
* np.subtract() → Subtraction
* np.multiply() → Multiplication
* np.divide() → Division
* np.power() → Power
* np.sqrt() → Square root
* np.exp() → Exponential
* np.log() → Logarithm
* np.sin(), np.cos(), np.tan() → Trigonometry

4. Statistical Functions


* np.mean() → Average
* np.median() → Middle value
* np.std() → Standard deviation
* np.var() → Variance
* np.min() → Minimum
* np.max() → Maximum
* np.sum() → Total
* np.argmin() → Index of min
* np.argmax() → Index of max

5. Searching & Sorting Functions


* np.sort() → Sort array
* np.argsort() → Indices of sorted
* np.where() → Condition check
* np.searchsorted() → Find position
* np.unique() → Unique values

6. Linear Algebra Functions


* np.dot() → Dot product
* np.matmul() → Matrix multiplication
* np.linalg.inv() → Inverse matrix
* np.linalg.det() → Determinant
* np.linalg.eig() → Eigenvalues

7. Random Functions


* np.random.rand() → Random values
* np.random.randn() → Normal distribution
* np.random.randint() → Random integers
* np.random.choice() → Random selection
* np.random.shuffle() → Shuffle array

8. Shape & Info Functions


* np.shape() → Shape of array
* np.size() → Total elements
* np.ndim() → Dimensions
* np.dtype() → Data type




In [73]:
# array

import numpy as np

n1 = np.array([3, 4, 5, 7, 2])
print(n1*2)

[ 6  8 10 14  4]


In [74]:
# list

l2 = ([2, 3, 4, 5], [4, 5, 2, 6], [6, 7, 4, 3])
print(l2)

([2, 3, 4, 5], [4, 5, 2, 6], [6, 7, 4, 3])


In [75]:
# 2D array

import numpy as np

l2 = np.array([[2, 3, 4, 5], [4, 5, 2, 6], [6, 7, 4, 3]])
print(l2)

[[2 3 4 5]
 [4 5 2 6]
 [6 7 4 3]]


In [76]:
# Shape & Info Functions


# np.shape() → Shape of array
# np.size() → Total elements
# np.ndim() → Dimensions
# np.dtype() → Data type

print(l2.shape)
print(l2.ndim)
print(l2.size)
print(l2.dtype)
print(l2.itemsize)

(3, 4)
2
12
int64
8


In [77]:
# Statistical Functions


# np.mean() → Average
# np.median() → Middle value
# np.std() → Standard deviation
# np.var() → Variance
# np.min() → Minimum
# np.max() → Maximum
# np.sum() → Total
# np.argmin() → Index of min
# np.argmax() → Index of max

print("sum : ", np.sum(l2))
print("std : ", np.std(l2))
print("var : ", np.var(l2))
print("min : ", np.min(l2))
print("max : ", np.max(l2))
print("mean : ", np.mean(l2))
print("median : ", np.median(l2))
print("argmin : ", np.argmin(l2))
print("argmax : ", np.argmax(l2))


sum :  51
std :  1.5343293866268306
var :  2.3541666666666665
min :  2
max :  7
mean :  4.25
median :  4.0
argmin :  0
argmax :  9


In [78]:
print(l2)

[[2 3 4 5]
 [4 5 2 6]
 [6 7 4 3]]


In [79]:
print("sum : ", np.sum(l2 , axis=1))
print("std : ", np.std(l2 , axis=1))
print("var : ", np.var(l2 , axis=1))
print("min : ", np.min(l2 , axis=1))
print("max : ", np.max(l2 , axis=1))
print("mean : ", np.mean(l2 , axis=1))
print("median : ", np.median(l2 , axis=1))
print("argmin : ", np.argmin(l2 , axis=1))
print("argmax : ", np.argmax(l2 , axis=1))

sum :  [14 17 20]
std :  [1.11803399 1.47901995 1.58113883]
var :  [1.25   2.1875 2.5   ]
min :  [2 2 3]
max :  [5 6 7]
mean :  [3.5  4.25 5.  ]
median :  [3.5 4.5 5. ]
argmin :  [0 2 3]
argmax :  [3 3 1]


In [80]:
l3 = np.array([[[2,3,4,5], [3,6,8,4], [4,5,2,1]],
      [[2,3,4,5], [3,6,8,4], [4,5,2,1]]])
print(l3)

[[[2 3 4 5]
  [3 6 8 4]
  [4 5 2 1]]

 [[2 3 4 5]
  [3 6 8 4]
  [4 5 2 1]]]


In [81]:
print(l3.shape)
print(l3.ndim)
print(l3.size)
print(l3.dtype)
print(l3.itemsize)

(2, 3, 4)
3
24
int64
8


In [82]:
print(np.sum(l3, axis=0))
print()
print(np.sum(l3, axis=1))
print()
print(np.sum(l3, axis=2))


[[ 4  6  8 10]
 [ 6 12 16  8]
 [ 8 10  4  2]]

[[ 9 14 14 10]
 [ 9 14 14 10]]

[[14 21 12]
 [14 21 12]]


In [83]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [84]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
# Array Creation Functions

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
# Random Functions

np.random.randint(0,10)

7

In [87]:
np.random.randint(0,10, (3,4))

array([[3, 2, 6, 9],
       [9, 1, 1, 5],
       [6, 5, 9, 5]])

In [88]:
n4 = np.random.randint(0,10, (3,4))
print(n4)

[[1 9 8 9]
 [5 8 6 4]
 [8 0 5 1]]


In [89]:
n5 = np.random.randint(0,10, (2,4))
print(n5)

[[4 1 8 8]
 [6 6 3 7]]


In [90]:
np.vstack((n4,n5))

array([[1, 9, 8, 9],
       [5, 8, 6, 4],
       [8, 0, 5, 1],
       [4, 1, 8, 8],
       [6, 6, 3, 7]])

In [91]:
np6 = np.random.randint(0,10, (2,2))
print(np6)

[[0 0]
 [1 2]]


In [92]:
np.hstack((n5,np6))

array([[4, 1, 8, 8, 0, 0],
       [6, 6, 3, 7, 1, 2]])

In [93]:
# Array Creation Functions

import numpy as np

n1 = np.arange(0,36)    # array + range
print(n1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [94]:
# 36 - (1,36), (36,1), (2,18), (18,2), (3,12), (12,3), (4,9), (9,4), (6,6)
# Total elements same rehne chahiye!
# 36 elements → 6×6 = 36

n2 = n1.reshape(6,6)
print(n2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [95]:
# Slicing Rule - n2[row_start:row_end, col_start:col_end]

n2[2:5 , 2:6]

array([[14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [96]:
n2[2:6 , 1:3]

array([[13, 14],
       [19, 20],
       [25, 26],
       [31, 32]])

In [97]:
print(n2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [98]:
# 1D slicing array

n2[5::]

array([[30, 31, 32, 33, 34, 35]])

In [99]:
# 2D slicing array

n2[5:,:]

array([[30, 31, 32, 33, 34, 35]])

In [100]:
n2[:,-1:]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [101]:
n3 = np.array([[2,3,4,5], [7,6,3,1], [1,3,8,5], [4,2,1,6]])
print(n3)

[[2 3 4 5]
 [7 6 3 1]
 [1 3 8 5]
 [4 2 1 6]]


In [102]:
k = 2
print(n3 * 2)

[[ 4  6  8 10]
 [14 12  6  2]
 [ 2  6 16 10]
 [ 8  4  2 12]]


In [103]:
print(n3)

[[2 3 4 5]
 [7 6 3 1]
 [1 3 8 5]
 [4 2 1 6]]


In [104]:
k1 = [2,3,1,5]
print(n3 * k1)

[[ 4  9  4 25]
 [14 18  3  5]
 [ 2  9  8 25]
 [ 8  6  1 30]]


In [105]:
# Linear aigebra operations

a = np.array([[2,3,4,1], [4,2,3,1]])
print(a)

[[2 3 4 1]
 [4 2 3 1]]


In [106]:
b = np.array([[2,1,3,2], [3,2,4,1]])
print(b)

[[2 1 3 2]
 [3 2 4 1]]


In [107]:
np.transpose(b)

array([[2, 3],
       [1, 2],
       [3, 4],
       [2, 1]])

In [108]:
np.dot(a,np.transpose(b))

array([[21, 29],
       [21, 29]])

In [109]:
# 3x + 2y + z = 10
# 2x + y + 5z = 15
# x + y + z = 5

A = np.array([[3,2,1], [2,1,5], [1,1,1]])
print(A)

[[3 2 1]
 [2 1 5]
 [1 1 1]]


In [110]:
x = np.array([['x'], ['y'], ['z']])
print(x)

[['x']
 ['y']
 ['z']]


In [111]:
B = np.array([[10], [15], [5]])
print(B)

[[10]
 [15]
 [ 5]]


In [112]:
Ainv =np.linalg.inv(A)
print(Ainv)

[[ 0.8  0.2 -1.8]
 [-0.6 -0.4  2.6]
 [-0.2  0.2  0.2]]


In [113]:
x = np.dot(Ainv,B)
print(x)

[[2.]
 [1.]
 [2.]]


In [114]:
np.dot(A,x)

array([[10.],
       [15.],
       [ 5.]])